<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.36.2" />
    <PackageReference Include="Grpc.Core.Api" Version="2.84.0" />
    <PackageReference Include="Grpc.Tools" Version="2.84.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\**\*.proto" ProtoRoot="Protos" GrpcServices="Both" />
  </ItemGroup>

</Project>
