// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Valetax.Wallets.Api.Persistence;

#nullable disable

namespace Valetax.Wallets.Api.Persistence.Migrations
{
    [DbContext(typeof(WalletsDbContext))]
    partial class WalletsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Valetax.Wallets.Api.Domain.Wallet", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("OwnerId");

                    b.ToTable("Wallets", (string)null);
                });

            modelBuilder.Entity("Valetax.Wallets.Api.Domain.WalletPayout", b =>
                {
                    b.Property<Guid>("CommissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("CommissionId");

                    b.HasIndex("WalletId", "PaidAt");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("WalletId", "PaidAt"), new[] { "Amount" });

                    b.ToTable("WalletPayouts", null, t =>
                        {
                            t.HasCheckConstraint("CK_WalletPayouts_Amount", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Valetax.Wallets.Api.Domain.WalletPayout", b =>
                {
                    b.HasOne("Valetax.Wallets.Api.Domain.Wallet", null)
                        .WithMany("Payouts")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Valetax.Wallets.Api.Domain.Wallet", b =>
                {
                    b.Navigation("Payouts");
                });
#pragma warning restore 612, 618
        }
    }
}
