// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Valetax.Api.Persistence;

#nullable disable

namespace Valetax.Api.Persistence.Migrations
{
    [DbContext(typeof(CommissionsDbContext))]
    partial class CommissionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Valetax.Api.Domain.Commission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfitEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipientExternalId")
                        .HasColumnType("uuid");

                    b.Property<int>("SchemaType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfitEventId", "Level")
                        .IsUnique();

                    b.ToTable("Commissions", (string)null);
                });

            modelBuilder.Entity("Valetax.Api.Domain.CommissionSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("SchemaType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CommissionSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SchemaType = 0
                        });
                });

            modelBuilder.Entity("Valetax.Api.Domain.ProfitEvent", b =>
                {
                    b.Property<Guid>("ExternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartnerExternalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Profit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SchemaType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ExternalId");

                    b.HasIndex("CreatedAt")
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("NextAttemptAt")
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("PartnerExternalId", "CreatedAt");

                    b.ToTable("ProfitEvents", (string)null);
                });

            modelBuilder.Entity("Valetax.Api.Domain.Commission", b =>
                {
                    b.HasOne("Valetax.Api.Domain.ProfitEvent", null)
                        .WithMany("Commissions")
                        .HasForeignKey("ProfitEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Valetax.Api.Domain.ProfitEvent", b =>
                {
                    b.Navigation("Commissions");
                });
#pragma warning restore 612, 618
        }
    }
}
