<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Valetax.Infrastructure\Valetax.Infrastructure.csproj" />
    <ProjectReference Include="..\Valetax.Partners.Api.Contracts\Valetax.Partners.Api.Contracts.csproj" />
    <ProjectReference Include="..\Valetax.Wallets.Api.Grpc\Valetax.Wallets.Api.Grpc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\.dockerignore">
      <Link>.dockerignore</Link>
      <DependentUpon>Dockerfile</DependentUpon>
    </Content>
  </ItemGroup>

</Project>
